services:
  back-end:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/home/app
    networks:
      - backend

  client:
    image: node:22-alpine
    command: sh -c "npm ci && npm run dev -- --host"
    working_dir: /app
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - backend

networks:
  backend:
